# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.cache/wt [current_project]
set_property parent.project_path D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.4 [current_project]
set_property ip_repo_paths d:/Major_Project/ip_cores [current_project]
set_property ip_output_repo d:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files d:/Major_Project/Zedboard_OLED_2018/vivado_proj/Zedboard-OLED.srcs/sources_1/imports/src/other/characterLib.coe
add_files d:/Major_Project/Zedboard_OLED_2018/vivado_proj/Zedboard-OLED.srcs/sources_1/imports/src/other/init_sequence.coe
add_files d:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/bd/design_1/ip/design_1_mlp_oled_0_1/src/characterLib.coe
add_files d:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/bd/design_1/ip/design_1_mlp_oled_0_1/src/init_sequence.coe
read_mem {
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/b_1_8.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/w_1_13.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/b_2_5.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/w_1_21.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/w_1_7.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/b_1_12.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/b_2_12.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/w_2_13.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/b_1_14.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/w_2_4.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/b_2_7.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/b_1_22.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/b_3_4.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/w_3_1.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/b_3_0.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/b_2_3.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/w_2_2.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/sigContent.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/b_1_10.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/w_1_5.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/w_1_11.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/b_1_6.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/b_2_14.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/w_2_15.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/w_3_8.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/b_2_16.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/b_1_19.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/w_1_23.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/b_1_24.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/b_3_2.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/w_2_0.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/b_1_18.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/w_2_9.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/w_2_17.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/b_2_1.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/b_2_18.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/b_1_25.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/w_1_26.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/b_1_27.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/w_1_17.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/b_1_5.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/b_3_8.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/w_1_2.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/w_3_5.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/b_1_1.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/w_1_0.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/w_2_7.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/b_1_29.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/w_1_15.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/w_1_28.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/b_2_8.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/w_1_9.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/b_1_20.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/b_3_6.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/w_2_19.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/w_3_3.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/b_1_16.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/b_1_3.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/b_2_11.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/w_2_10.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/b_1_21.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/w_2_5.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/b_2_6.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/w_1_22.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/b_3_3.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/w_3_2.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/w_1_20.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/w_2_3.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/b_1_9.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/b_2_13.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/w_1_12.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/w_2_12.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/b_1_13.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/w_1_29.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/w_1_6.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/b_2_15.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/w_3_9.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/b_1_0.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/w_3_0.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/b_3_1.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/b_1_23.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/w_1_24.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/b_1_7.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/b_2_4.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/w_2_14.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/w_2_1.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/w_1_19.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/w_1_10.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/b_1_11.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/w_1_4.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/w_3_7.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/w_1_18.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/b_2_0.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/b_2_17.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/b_3_7.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/w_2_18.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/w_3_6.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/b_1_4.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/w_1_3.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/w_1_25.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/b_2_2.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/b_3_9.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/w_2_8.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/w_1_16.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/w_2_16.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/b_1_17.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/b_1_26.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/b_1_15.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/b_3_5.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/b_2_10.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/w_1_1.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/w_2_11.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/w_3_4.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/b_2_9.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/b_1_2.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/b_2_19.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/w_2_6.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/w_1_8.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/w_1_27.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/w_1_14.mif
  D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/imports/rtl/b_1_28.mif
}
read_verilog -library xil_defaultlib D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
add_files D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all d:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_1/design_1_processing_system7_0_1.xdc]
set_property used_in_implementation false [get_files -all d:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_0_2/design_1_axi_dma_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_0_2/design_1_axi_dma_0_2.xdc]
set_property used_in_implementation false [get_files -all d:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_0_2/design_1_axi_dma_0_2_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/bd/design_1/ip/design_1_mlp_oled_0_1/src/charLib/charLib_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/bd/design_1/ip/design_1_mlp_oled_0_1/src/init_sequence_rom/init_sequence_rom_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/bd/design_1/ip/design_1_mlp_oled_0_1/src/pixel_buffer/pixel_buffer_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/bd/design_1/ip/design_1_mlp_oled_0_1/src/constraintsnew.xdc]
set_property used_in_implementation false [get_files -all d:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_5/bd_886d_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_8/bd_886d_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_6/bd_886d_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_7/bd_886d_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_1/bd_886d_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_1/bd_886d_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all d:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_50M_0/design_1_rst_ps7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_50M_0/design_1_rst_ps7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all d:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_50M_0/design_1_rst_ps7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/design_1_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/bd/design_1/design_1_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/constrs_1/imports/new/constraintsnew.xdc
set_property used_in_implementation false [get_files D:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/constrs_1/imports/new/constraintsnew.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top design_1_wrapper -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef design_1_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
