# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/bd/design_1/ip/design_1_mlp_oled_0_1/design_1_mlp_oled_0_1.xci
# IP: The module: 'design_1_mlp_oled_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/bd/design_1/ip/design_1_mlp_oled_0_1/src/charLib/charLib.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==charLib || ORIG_REF_NAME==charLib} -quiet] -quiet

# IP: d:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/bd/design_1/ip/design_1_mlp_oled_0_1/src/init_sequence_rom/init_sequence_rom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==init_sequence_rom || ORIG_REF_NAME==init_sequence_rom} -quiet] -quiet

# IP: d:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/bd/design_1/ip/design_1_mlp_oled_0_1/src/pixel_buffer/pixel_buffer.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pixel_buffer || ORIG_REF_NAME==pixel_buffer} -quiet] -quiet

# XDC: d:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/bd/design_1/ip/design_1_mlp_oled_0_1/src/charLib/charLib_ooc.xdc

# XDC: d:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/bd/design_1/ip/design_1_mlp_oled_0_1/src/init_sequence_rom/init_sequence_rom_ooc.xdc

# XDC: d:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/bd/design_1/ip/design_1_mlp_oled_0_1/src/pixel_buffer/pixel_buffer_ooc.xdc

# XDC: d:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/bd/design_1/ip/design_1_mlp_oled_0_1/src/constraintsnew.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_mlp_oled_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/bd/design_1/ip/design_1_mlp_oled_0_1/design_1_mlp_oled_0_1.xci
# IP: The module: 'design_1_mlp_oled_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/bd/design_1/ip/design_1_mlp_oled_0_1/src/charLib/charLib.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==charLib || ORIG_REF_NAME==charLib} -quiet] -quiet

# IP: d:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/bd/design_1/ip/design_1_mlp_oled_0_1/src/init_sequence_rom/init_sequence_rom.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==init_sequence_rom || ORIG_REF_NAME==init_sequence_rom} -quiet] -quiet

# IP: d:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/bd/design_1/ip/design_1_mlp_oled_0_1/src/pixel_buffer/pixel_buffer.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pixel_buffer || ORIG_REF_NAME==pixel_buffer} -quiet] -quiet

# XDC: d:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/bd/design_1/ip/design_1_mlp_oled_0_1/src/charLib/charLib_ooc.xdc

# XDC: d:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/bd/design_1/ip/design_1_mlp_oled_0_1/src/init_sequence_rom/init_sequence_rom_ooc.xdc

# XDC: d:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/bd/design_1/ip/design_1_mlp_oled_0_1/src/pixel_buffer/pixel_buffer_ooc.xdc

# XDC: d:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/bd/design_1/ip/design_1_mlp_oled_0_1/src/constraintsnew.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_mlp_oled_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
