# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/ip/init_sequence_rom/init_sequence_rom.xci
# IP: The module: 'init_sequence_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/ip/init_sequence_rom/init_sequence_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'init_sequence_rom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/ip/init_sequence_rom/init_sequence_rom.xci
# IP: The module: 'init_sequence_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Major_Project/zynet_Project_incorporated_OLED/MLP_oled/MLP_oled.srcs/sources_1/ip/init_sequence_rom/init_sequence_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'init_sequence_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
